version: "3.9"

services:
  api:
    image: link-shortener:latest
    container_name: linksh
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:16
    container_name: pgdb
    env_file:
      - .env
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  database:

networks:
  app-network:
